// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RuleBuilderInfra.Persistence;

#nullable disable

namespace RuleBuilderInfra.Persistence.Migrations.MainDatabaseMigrations
{
    [DbContext(typeof(MainDatabase))]
    partial class MainDatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RuleBuilderInfra.Domain.Entities.FakeDataEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Distributer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Movie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("fakeDataEntities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Distributer = "Paramond",
                            Movie = "Spider",
                            Province = "Ontario"
                        },
                        new
                        {
                            Id = 2,
                            Distributer = "Paramond",
                            Movie = "Sinderella",
                            Province = "Quebec"
                        },
                        new
                        {
                            Id = 3,
                            Distributer = "Disney",
                            Movie = "The Notebook",
                            Province = "Calgary"
                        },
                        new
                        {
                            Id = 4,
                            Distributer = "Lionsgate",
                            Movie = "SpiderMan",
                            Province = "Ontario"
                        },
                        new
                        {
                            Id = 5,
                            Distributer = "Lionsgate",
                            Movie = "The Notebook",
                            Province = "Quebec"
                        },
                        new
                        {
                            Id = 6,
                            Distributer = "Disney",
                            Movie = "Notebook",
                            Province = "Quebec"
                        },
                        new
                        {
                            Id = 7,
                            Distributer = "Disney",
                            Movie = "Sinderella",
                            Province = "Quebec"
                        });
                });

            modelBuilder.Entity("RuleBuilderInfra.Domain.Entities.ProvincesEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("provincesEntities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ON",
                            Name = "Onatrio"
                        },
                        new
                        {
                            Id = 2,
                            Code = "QB",
                            Name = "Quebec"
                        },
                        new
                        {
                            Id = 3,
                            Code = "MN",
                            Name = "Montreal"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
